# Generated by Django 6.0.1 on 2026-04-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(help_text='Select one genre', related_name='movies', to='catalog.genre'),
        ),
    ]
